spring:
  application:
    name: spring-cloud-learn-provider-dept
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.com:8761/eureka/,http://eureka2.com:8762/eureka/