spring:
  application:
    name: spring-cloud-learn-consumer-dept-ribbon
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/