spring:
  application:
    name: spring-cloud-learn-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yuanqinnan/spring-cloud-config
          search-paths: respo
          username: 1546022688@qq.com
          password: GitYqn68926

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

